[package]
name = "day10"
version = "0.1.0"
authors = ["Florian Riedl <florian.riedl@student.tugraz.at>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]